config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/homepage'

  get 'static_pages/about'

  devise_for :users, controllers: {sessions: 'users/sessions'}
  resources :todo_lists do
    resources :list_items do
      member do
        patch :complete
      end
    end
  end

  root 'static_pages#homepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #JSON API
  # namespace 'api' do
  #   namespace 'v1' do
  #     jsonapi_resources :todo_lists
  #     jsonapi_resources :list_items
  #   end
  # end

  namespace :api do
    namespace :v1 do
      jsonapi_resources :todo_lists
      jsonapi_resources :list_items do
        member do
          patch :complete
        end
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list_item.rb
class ListItem < ApplicationRecord
  belongs_to :todo_list

  validates :name, presence: true

  scope :completed, -> { where.not(completed: nil) }
  scope :not_completed, -> { where(completed: nil) }

  def toggle_complete
    if completed?
      update_attribute(:completed, nil)
    else
      update_attribute(:completed, Time.now)
    end
  end

  def completed?
    !completed.blank?
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :user
  has_many :list_items, dependent: :destroy

  validates :name, presence: true
  validates :user, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :todo_lists, dependent: :destroy

  validates :email, presence: true

  def as_json(options={})
    token = create_token(options)
    super(options).merge({token: token})
  end

  def create_token(options)
    JWTWrapper.encode({"user_id"=>id.to_s})
  end
end

app/controllers/api/v1/api_base_controller.rb
module Api
  module V1
    class ApiBaseController < JSONAPI::ResourceController
      include CurrentUser
      protect_from_forgery with: :null_session
      before_action :authenticate_user!
    end
  end
end

app/controllers/api/v1/list_items_controller.rb
module Api
  module V1
    class ListItemsController < ApiBaseController
      def complete
        id = params[:id]
        list_item = ListItem.find(params[:id])
        if list_item
          list_item.toggle_complete
          render json: {
              data: {
                  id: list_item.id.to_s,
                  type: 'list-items',
                  attributes: list_item.as_json
              }
            }, status: 200
        else
          render json: {
              data: {
                  error: {
                      message: "Record with id #{id} not found",
                  }
              }
          }, status: 404
        end
      end
    end
  end
end

app/controllers/api/v1/todo_lists_controller.rb
module Api
  module V1
    class TodoListsController < ApiBaseController
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  respond_to :html, :json
  protect_from_forgery with: :null_session

  def after_sign_in_path_for(resource)
    todo_lists_path
  end
end

app/controllers/concerns/current_user.rb
module CurrentUser
  def context
    { current_user: current_user }
  end
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_todo_list
  before_action :set_list_item, except: [:create]


  # POST /list_items
  # POST /list_items.json
  def create
    @todo_item = @todo_list.list_items.create(list_item_params)
    redirect_to @todo_list
  end

  def destroy
    @list_item = @todo_list.list_items.find(params[:id])
    if @list_item.destroy
      flash[:success] = "Zadanie usunięte."
    else
      flash[:error] = "Zadanie nie mogło zostac usunięte."
    end
    redirect_to @todo_list
  end

  def complete
    @list_item.toggle_complete

    if @list_item.completed?
      redirect_to @todo_list, notice: 'Zadanie oznaczone jako wykonane.'
    else
      redirect_to @todo_list, notice: 'Zadanie oznaczone jako niewykonane.'
    end
  end

  private
    def set_todo_list
      @todo_list = TodoList.find(params[:todo_list_id])
    end

    def set_list_item
      @list_item = @todo_list.list_items.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_item_params
      params[:list_item].permit(
                          :name,
                          :description,
                          :completed,
                          :todo_list_id
                        )
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def homepage
  end

  def about
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = current_user.todo_lists
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)
    @todo_list.user = current_user
    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: "Lista #{@todo_list.name} stworzona." }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: "Lista #{@todo_list.name} uaktualniona." }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_path, notice: "Lista #{@todo_list.name} usunięta." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:name, :description)
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(link_path, root = false)
    if current_page?(link_path) ||
       current_page?(root_path) && root ||
       link_path.include?('todo_lists') && request.controller_class == TodoListsController
      "menu-active"
    else
      ""
    end
  end
end

app/helpers/jwt_wrapper.rb
# Helper module for you to use on your app and in your Strategy
# Don't add "Helper" to its name and rails won't load it has a view helper module.
# "app/helpers/jwt_wrapper.rb"

module JWTWrapper
  extend self

  def encode(payload, expiration = nil)
    expiration ||= Rails.application.secrets.jwt_expiration_hours

    payload = payload.dup
    payload['exp'] = expiration.to_i.hours.from_now.to_i

    JWT.encode payload, Rails.application.secrets.jwt_secret
  end

  def decode(token)
    begin
      decoded_token = JWT.decode token, Rails.application.secrets.jwt_secret

      decoded_token.first
    rescue
      nil
    end
  end
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/_flash_message.html.haml
- flash.each do |key, value|
  - key = "success" if key == "notice"
  - key = "danger" if key == "error"
  %div{:class => "alert alert-#{key}"}
    %button.close{"data-dismiss" => "alert", :type => "button"} ×
    %strong= value

app/views/layouts/_footer.html.haml
-#%footer.footer
-#  .container
-#    %span.text-muted Place sticky footer content here.

%footer.footer
  .container
    .copyright
      \© Copyright
      %strong Radosław Stolarski, 2018
    .credits
/ #footer

app/views/layouts/_navbar.html.haml
%header#header
  .container
    #logo.pull-left
      %h1
        %a.scrollto
          = link_to root_path do
            Todo App
            %span z warstwą API
      / Uncomment below if you prefer to use an image logo
      / <a href="#body"><img src="img/logo.png" alt="" title="" /></a>
    %nav#nav-menu-container
      %ul.nav-menu
        %li{class: active_class(static_pages_homepage_path, true)}
          = link_to 'Strona główna', static_pages_homepage_path
        %li{class: active_class(static_pages_about_path)}
          = link_to 'O pracy', static_pages_about_path
        - if current_user
          %li{class: active_class(todo_lists_path)}
            = link_to 'Moje listy', todo_lists_path
          %li{class: active_class(destroy_user_session_path)}
            = link_to 'Wyloguj się', destroy_user_session_path, method: :delete
        - else
          %li{class: active_class(new_user_session_path)}
            = link_to 'Zaloguj się', new_user_session_path
          %li{class: active_class(new_user_registration_path)}
            = link_to 'Zarejestruj się', new_user_registration_path
    / #nav-menu-container
/ #header

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TodoAppWithApi
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = stylesheet_link_tag 'application',                                    |
      'https://fonts.googleapis.com/css?family=Open+Sans:400&subset=latin', |
      media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'application', 'https://fonts.googleapis.com/icon?family=Material+Icons'
    = stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Muli:300'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
  %body#body
    = render 'layouts/navbar'
    = render 'layouts/flash_message'
    %main#main
      = yield
      .push
    = render 'layouts/footer'

app/views/list_items/_form.html.haml
= form_for([@todo_list, @todo_list.list_items.build]) do |f|
  = f.text_field :name, placeholder: "Nowe zadanie"
  = f.text_field :description, placeholder: "Opis (opcjonalnie)"
  = f.submit 'Utwórz nowe zadanie', class: 'btn-projects'
%br
%br

app/views/list_items/_list_item.html.haml
- if list_item.completed?

- else

app/views/list_items/edit.html.haml
%h1 Editing List Item
= render 'form', list_item: @list_item
= link_to 'Show', @list_item
|
= link_to 'Back', list_items_path

app/views/list_items/index.html.haml
%h1 List Items
%table
  %thead
    %tr
      %th Name
      %th Description
      %th Completed
      %th Todo list
      %th{:colspan => "3"}
  %tbody
    - @list_items.each do |list_item|
      %tr
        %td= list_item.name
        %td= list_item.description
        %td= list_item.completed
        %td= list_item.todo_list
        %td= link_to 'Show', list_item
        %td= link_to 'Edit', edit_list_item_path(list_item)
        %td= link_to 'Destroy', list_item, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New List Item', new_list_item_path

app/views/list_items/new.html.haml
%h1 New List Item
= render 'form', list_item: @list_item
= link_to 'Back', list_items_path

app/views/list_items/show.html.haml
%p
  %strong Name:
  = @list_item.name
%p
  %strong Description:
  = @list_item.description
%p
  %strong Completed:
  = @list_item.completed
%p
  %strong Todo list:
  = @list_item.todo_list
= link_to 'Edit', edit_list_item_path(@list_item)
|
= link_to 'Back', list_items_path

app/views/static_pages/about.html.haml
%section#services
  .container
    .section-header
      %h2 O pracy
    .row
      .col-lg-6
        .box.wow.fadeInLeft
          %h4.title Wstęp
          %p.description
            Autorem niniejszego serwisu jest Radosław Stolarski |
            Serwis ten stanowi integralną część pracy magisterskiej (kierunek: Elektroniczne |
            Przetwarzanie Informacji), przygotowanej pod kierunkiem prof. dra hab. Mariusza Flasińskiego |
            na Wydziale Zarządzania i Komunikacji Społecznej Uniwersytetu Jagiellońskiego.

      .col-lg-6
        .box.wow.fadeInRight
          %h4.title Opis
          %p.description
            Aplikacja w swojej podstawowej wersji webowej umożliwia założenie konta, zalogowanie się |
            a następnie tworzenie swoich list zadań z rzeczami do zrobienia. Po dodaniu zadania możliwe |
            jest oznaczenie go jako ukończonego oraz usunięcie. |
            Dodatkowo aplikacja jest wzbogacona o warstwę interfejsu API, który za pomocą REST umożliwia |
            dostęp do danych zgromadzonych w serwisie, ich modyfikację i usuwanie.
    .row
      .col-sm-12
        .box.wow.fadeInLeft
          %h4.title Jak korzystać z aplikacji w przeglądarce?
          %p.description
            Aby skorzystać z aplikacji w przeglądarce internetowej, wystarczy skorzystać z utworzonych wcześniej kont testowych
            i zalogować się ich danymi, przykładowe dane to: login
            %code user_1@test.pl,
            hasło
            %code password123
            lub utworzyć nowego użytkownika ze swoimi danymi.
        .box.wow.fadeInLeft
          %h4.title Jak korzystać z API
          %p.description
            Z API można połączyć się z każdej aplikacji / serwisu umożliwiającego wysyłanie zapytań HTTP. W przykładzie
            pokazuję, jak użyć do tego aplikacji Postman, ale równie dobrze można użyć do tego cURL czy też napisanego
            klienta w dowolnym języku, ktory umożliwi wysyłanie zapytań z użyciem HTTP.
          %br
            %ul
              %li
                I. Pobierz aplikację kompatybilną z systemem którego używasz ze strony
                %a{href: 'https://www.getpostman.com/apps'} https://www.getpostman.com/apps
              %li II. Zainstaluj i uruchom aplikację.
              %li
                III. Po uruchomieniu aplikacji:
                %ul
                  %li
                    1. Zmień czasownik
                    %code HTTP
                    na
                    %code POST
                  %li
                    2. Wpisz URL prowadzący do logowania się:
                    %code http://leszczyna.wzks.uj.edu.pl/12_stolarski/todo_app_with_api/users/sign_in.json
                  %li
                    3. Ustaw header: jako klucz wpisz
                    %code 'Content-Type'
                  %li
                    4. Jako wartość:
                    %code 'application/json'.
                = image_tag("instructions/instrukcja 1.jpg", class: 'img img-responsive')
              %li
                %br
                %br
                IV. Kolejny krok:
                %ul
                  %li 1. Przejdź do zakładki body
                  %li
                    2. Wybierz pole raw, aby wprowadzić dane do przesłania (użyty jest tu już istniejący użytkownik)
                  %li
                    3. Wprowadź dane.
                    %code
                      { |
                        "user": { |
                          "email":"user_1@test.pl", |
                          "password":"password123" |
                        } |
                      }
                  %li
                    4. Kliknij przycisk
                    %code 'Send'
                    , aby wysłać zapytanie.
                = image_tag("instructions/instrukcja 2.jpg", class: 'img img-responsive')
              %li
                %br
                %br
                V. Kopiowanie tokenu z odpowiedzi
                %ul
                  %li 1. Skopiuj odebrany token do schowka
              = image_tag("instructions/instrukcja 3.jpg", class: 'img img-responsive')
              %li
                %br
                %br
                VI. Wysyłanie autoryzowanego zapytania do API
                %ul
                  %li
                    1. Zmień czasownik HTTP na
                    %code GET
                  %li
                    2. Wprowadź nowy url:
                    %code http://leszczyna.wzks.uj.edu.pl/12_stolarski/todo_app_with_api/api/v1/todo-lists
                  %li 3. Wybierz sposób autoryzacji Bearer Token
                  %li 4. Wklej token ze schowka
                  %li 5. Kliknij przycisk "Send"
                  %li
                    6. W dolnym oknie powinna pokazać się odpowiedź od serwera w formacie
                    %code JSON
                    z danymi.
              = image_tag("instructions/instrukcja 4.jpg", class: 'img img-responsive')
              %li
                %br
                %br
                VII. Przykładowe URLe do użycia (do każdego potrzeba wcześniej tokenu, jak go zdobyć? Patrz punkt III i IV)
                %ul
                  %li
                    1. Pobranie list todo dla użytkownika:
                    %code http://leszczyna.wzks.uj.edu.pl/12_stolarski/todo_app_with_api/api/v1/todo-lists
                  %li
                    2. Pobranie list todo dla użytkownika wraz z listą zadań:
                    %code http://leszczyna.wzks.uj.edu.pl/12_stolarski/todo_app_with_api/api/v1/todo-lists/1?include=list-items
                  %li
                    3. Pobranie list todo dla użytkownika wraz z użyciem filtrowania:
                    %code http://leszczyna.wzks.uj.edu.pl/12_stolarski/todo_app_with_api/api/v1/todo-lists?filter[name]=Lista+1
                  %li
                    4. Pobranie list todo dla użytkownika wraz z użyciem paginacji oraz z dołączeniem zadań
                    %code http://leszczyna.wzks.uj.edu.pl/12_stolarski/todo_app_with_api/api/v1/todo-lists?page[size]=2&include=list-items
                  %li
                    4. Usunięcie listy (pamiętaj o zmianie czasownika HTTP na
                    %code DELETE
                    )
                    %code http://leszczyna.wzks.uj.edu.pl/12_stolarski/todo_app_with_api/api/v1/todo-lists/4

app/views/static_pages/homepage.html.haml
%section#intro
  .intro-content
    %h2 Praca magisterska
    %h3 Aplikacja ToDo w Ruby on Rails z warstwą API
    %div
      = link_to 'O pracy', static_pages_about_path, class: 'btn-get-started'
      - if current_user
        = link_to 'Wyloguj się', destroy_user_session_path, method: :delete, class: 'btn-projects'
      - else
        = link_to 'Logowanie', new_user_session_path, class: 'btn-projects'

app/views/todo_lists/_form.html.haml
= form_with(model: todo_list, local: true) do |form|
  - if todo_list.errors.any?
    #error_explanation
      %h2
        = pluralize(todo_list.errors.count, "error")
        prohibited this todo_list from being saved:
      %ul
        - todo_list.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :name, 'Nazwa'
    = form.text_field :name, id: :todo_list_name
  .field
    = form.label :description, 'Opis'
    = form.text_area :description, id: :todo_list_description
  .actions
    = form.submit 'Utwórz', class: 'btn-projects'

app/views/todo_lists/_list_items_completed.html.haml
- list_items_completed.each do |list_item|
  %li.todo-item.high
    .icon-check
      %i.pad-15.material-icons.md-36.md-light check_circle
    .icon-delete
      = link_to todo_list_list_item_path(list_item.todo_list,
                      list_item.id),
                      method: :delete,
                      data: { confirm: "Are you sure?" } do
        %i.pad-15.material-icons.md-36.md-light delete
    .content= list_item.description
  -#%li.todo-item.medium
  -#  .icon-check
  -#    %i.pad-15.material-icons.md-36.md-light check_circle
  -#  .icon-delete
  -#    %i.pad-15.material-icons.md-36.md-light delete
  -#  .content
  -#    Learn React
  -#%li.todo-item.low
  -#  .icon-check
  -#    %i.pad-15.material-icons.md-36.md-light check_circle
  -#  .icon-delete
  -#    %i.pad-15.material-icons.md-36.md-light delete
  -#  .content
  -#    Learn React

app/views/todo_lists/_list_items_in_progress.html.haml
- list_items_in_progress.each do |list_item|
  %li.todo-item.high{:draggable => "true"}
    .card
      %h3.todo-title
        %span.action
          = link_to  todo_list_list_item_path(list_item.todo_list, list_item.id), method: :delete, data: { confirm: "Are you sure?" } do
            %i.material-icons.md-36.icon-delete delete
          = link_to complete_todo_list_list_item_path(list_item.todo_list, list_item.id), method: :patch do
            %i.icon-checkbox-outline.material-icons.md-36.md-dark check_box_outline_blank
            %i.icon-checkbox.material-icons.md-36.md-light check_box
        %span.title= list_item.name
      %p.todo-description
        = list_item.description
  -#%span.todo-priority High
  -#%li.todo-item.new
  -#  .card
  -#    %h3.todo-title
  -#      %span.action
  -#        %i.complete.material-icons.md-36.md-light add_circle_outline
  -#      %span.title ADD A TODO

app/views/todo_lists/edit.html.haml
.container
  %h1 Edytuj listę
  = render 'form', todo_list: @todo_list
  = link_to 'Pokaż', @todo_list
  |
  = link_to 'Wróć', todo_lists_path

app/views/todo_lists/index.html.haml
%section#services
  .container
    .section-header
      %h2 Twoje listy zadań
      = link_to 'Nowa lista', new_todo_list_path, class: 'btn-projects'
    .row
      - @todo_lists.each do |todo_list|
        .col-lg-3
          .box.wow.fadeInLeft
            %a{href: todo_list_path(todo_list), style: 'width: 100%; height: 100%;top: 0;  bottom: 0;  right: 0;  left: 0;'}
              %h4.title
                =todo_list.name
              %p.description
                =todo_list.description.truncate(30)
              = link_to 'Edytuj', edit_todo_list_path(todo_list), class: 'btn btn-xs btn-warning'
              = link_to 'Usuń', todo_list, method: :delete, class: 'btn btn-xs btn-danger', data: { confirm: 'Jesteś pewien, że chcesz usunąć?' }

app/views/todo_lists/new.html.haml
.container
  %h1 Nowa lista zadań
  = render 'form', todo_list: @todo_list
  = link_to 'Wróć', todo_lists_path

app/views/todo_lists/show.html.haml
%section#services
  .container
    .section-header
      %h2
        = @todo_list.name

        = link_to 'Edytuj', edit_todo_list_path(@todo_list), class: 'btn btn-xs btn-warning'
        = link_to 'Usuń',                  |
          todo_list_path(@todo_list),        |
          class: 'btn btn-xs btn-danger',   |
          method: :delete,                   |
          data: { confirm: "Jesteś pewien?" }

      %p= @todo_list.description

    #todo_items_wrapper
      %section.todo-list-container
        #form
          = render "list_items/form"
        .todo-in-progress
          %h2.title Zadania w trakcie
          %ul#target.todo-list{:ondragstart => ""}
            = render partial: 'list_items_in_progress', locals: { list_items_in_progress: @todo_list.list_items.not_completed }
        .todo-completed
          %h2 Ukończone
          %ul.todo-list-completed
            = render partial: 'list_items_completed', locals: { list_items_completed: @todo_list.list_items.completed }